/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bridge_street_light_3.glb 
Author: Streetlights & ETC (https://sketchfab.com/daffyxxcoolxx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bridge-street-light-3-758491c162e74077950a67fda4953b6c
Title: Bridge street light 3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bridge_street_light_3.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.auto} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.Color_M04} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.Color_M09} />
        <mesh geometry={nodes.Material3.geometry} material={materials.Color_M09_1} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Color_M05} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.material} />
        <lineSegments geometry={nodes.Material2_4.geometry} material={materials.edge_color000255} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_M02_1} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.Color_M02} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Sumele_Hair} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Color_E05} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.Color_M00} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.Metal_Aluminum_Anodized} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.Metal_Aluminum_Anodized_0} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.Translucent_Glass_Gray} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.Metal_Rough} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.Metal_Corrogated_Shiny} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.Color_001} />
        <mesh geometry={nodes.Material3_3.geometry} material={materials.Color_M01} />
        <lineSegments geometry={nodes.Material2_16.geometry} material={materials.edge_color198198198255} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials.Metal_Brass_Ceiling} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials['FBR-2']} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials.Color_M06} />
        <mesh geometry={nodes.Material2_20.geometry} material={materials.Color_M03_1} />
        <lineSegments geometry={nodes.Material2_21.geometry} material={materials.edge_color226226226255} />
        <mesh geometry={nodes.Material2_22.geometry} material={materials['0132_LightGray']} />
        <mesh geometry={nodes.Material2_23.geometry} material={materials.matchpole34k2_1} />
        <mesh geometry={nodes.Material2_24.geometry} material={materials.Galvanized_steel} />
        <mesh geometry={nodes.Material2_25.geometry} material={materials.Metal_Rough_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/bridge_street_light_3.glb')
