/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car3.glb --transform --instance --precision=6
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_1'].geometry} material={materials.black} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_2'].geometry} material={materials.mattemetal} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_3'].geometry} material={materials.chrome} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_4'].geometry} material={materials.clearglass} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_5'].geometry} material={materials.windowglass} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_6'].geometry} material={materials.carpaint_second} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_7'].geometry} material={materials.darkglass} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_8'].geometry} material={materials.lightglass} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_9'].geometry} material={materials.mirror} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_10'].geometry} material={materials.interior} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_11'].geometry} material={materials.red} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_12'].geometry} material={materials.carpaint} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_13'].geometry} material={materials.rim} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_14'].geometry} material={materials.brakedisk} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_15'].geometry} material={materials.tire} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_16'].geometry} material={materials.LicPlate_white} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_17'].geometry} material={materials.LicPlate_black} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_18'].geometry} material={materials.LicPlate_blue} />
        <mesh geometry={nodes['W-Motors_Ghiath_Dubai_Police_2021_19'].geometry} material={materials.LicPlate_yellow} />
      </group>
    </group>
  )
}

useGLTF.preload('/car3-transformed.glb')
