/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dubai1.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/dubai1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        {/* <PerspectiveCamera name="Cam_01" makeDefault={false} far={10000000000} near={0.01} fov={31.417} position={[-0.437, 0.915, -2.097]} rotation={[0.286, 0.036, -0.011]} /> */}
        <mesh name="Bridge_1" geometry={nodes.Bridge_1.geometry} material={materials.White} position={[-0.434, -0.171, -1.682]} scale={0.079} />
        <mesh name="Areasbuilding" geometry={nodes.Areasbuilding.geometry} material={materials.Mat} position={[-4.119, 0, -6.8]} rotation={[-Math.PI / 2, 0, -0.236]} scale={100} />
        <mesh name="Extrude" geometry={nodes.Extrude.geometry} material={nodes.Extrude.material} position={[-0.394, -0.531, 3.474]} />
        {/* <mesh name="water" geometry={nodes.water.geometry} material={materials.water} position={[-0.438, -0.166, -0.751]} rotation={[0, 0.694, 0]} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/dubai1.glb')
