/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 street.glb --instance 
Files: street.glb [1.86MB] > /Users/basharahammed/Desktop/projects/dp-drone/public/images/models/street-transformed.glb [222.79KB] (88%)
Author: Streetlights & ETC (https://sketchfab.com/daffyxxcoolxx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bridge-street-light-3-758491c162e74077950a67fda4953b6c
Title: Bridge street light 3
*/

import React from 'react'
import { Merged, useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/street-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Material2_1.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_2.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_3.geometry} material={materials.Metal_Aluminum_Anodized} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_4.geometry} material={materials.Metal_Aluminum_Anodized_0} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_5.geometry} material={materials.Metal_Rough} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_6.geometry} material={materials.Metal_Corrogated_Shiny} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_7.geometry} material={materials.Metal_Brass_Ceiling} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_8.geometry} material={materials['0132_LightGray']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_9.geometry} material={materials.Galvanized_steel} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_10.geometry} material={materials.Metal_Rough_0} rotation={[-Math.PI / 2, 0, 0]} />

      <Merged meshes={nodes}>
      {({ Material2, Material2_2, Material2_3 }) => (
        <>
          <Material2 />
          <Material2_2 position={[1, 2, 3]} />
          <Material2_3 position={[4, 5, 6]} />
        </>
      )}
    </Merged>


    </group>
  )
}

useGLTF.preload('/street-transformed.glb')
