import { Anek_Malayalam } from "next/font/google";
import "./globals.css";
import GlobalProviders from "@/components/GlobalProviders";
import nextFetch from "@/utils/nextFetch";
import { GLOBAL } from "@/constants/apiRoutes";
const inter = Anek_Malayalam({
  subsets: ["latin"],
  variable: '--font-inter',
  axes:['wdth'],
  weight: ['variable']
});

export const metadata = {
  title: "Dubai Police | Home page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable}`}>
          <GlobalProviders >
            {children}
          </GlobalProviders>
      </body>
    </html>
  );
}
