// import { Anek_Malayalam } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import "./icon-font.css"
import GlobalProviders from "@/components/GlobalProviders";
import nextFetch from "@/utils/nextFetch";
import { GLOBAL } from "@/constants/apiRoutes";
import Header from "@/components/Header";
import StickyBar from '@/components/StickyBar';

// const inter = Anek_Malayalam({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   axes: ["wdth"],
//   weight: ["variable"],
// });


const dp_font = localFont({
  src: [
    {
      path: './fonts/Dubai-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Dubai-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Dubai-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Dubai-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
})

export const metadata = {
  title: "Dubai Police | Home page",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dp_font.className} ${dp_font.variable}`}>
        <GlobalProviders>
          <Header />
          <StickyBar />
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
